### ISSUE TITLE
Rust CryptoNight

### ISSUE THREAD

**Issue by Boog900** [Cuprate/cuprate#28]
Currently the `cryptonight` crate is the only crate in this repo that is not a Rust re-write and is instead bindings to the c impl, I would prefer to use a fully Rust impl.

**Comment by Boog900** [comment]
We could do that but we would also have to account for every network as well as potential future ones (mainnet, testnet, stagenet) so I would rather have to use bindings than just skip it.

That is also the reason why I haven't prioritized a Rust impl (it's not used on current Monero).

**Comment by dan-da** [comment]
I took a quick look at the cryptonight c source code in this repo.

It seems like porting all that directly from C to rust would be a significant amount of work.

otoh, there exist rust crates for several of the crypto primitives such as aes, blake, groestl, etc.  If we are able to use these, that would seem a faster path.  Is that what you have in mind?

anyway, I might be able to help out with this.

**Comment by dan-da** [comment]
Another possibility might be to use [c2rust](https://c2rust.com/) to transpile the C code into unsafe rust, as a starting point.

**Comment by Boog900** [comment]
Yeah I should have been more clear, I was thinking of using those crates and not doing a total re-write.

Although interesting, IMO I don't think that c2rust transpiler will be very helpful. I think a clean start would be beter instead of a line-for-line re-write. 

I would very much appreciate you working on this if you are able to :) There are a few Rust CryptoNight impls but none of them that have much, if any, use and some even say there are known bugs but don't actually say what the bugs are, you may find them useful as example though.

**Comment by Boog900** [comment]
Yeah a couple things I don't like about that crate: it hasn't been updated in a while, it has had very little (if any) usage and you can't actually use it as it depends on a yanked crate. 

Also it only implements one variant of cryptonote, standard 8, I think this is the initial Monero variant but am not 100% so it's missing v1,2 and R

**Comment by dan-da** [comment]
That is helpful, thx.

Ok, I took a look at cryptonight-hash code.   You are correct they only impl one version, called Cryptonight version 0 [here](https://github.com/bertptrs/cryptonight-hash/blob/5ee91ac2d2d216d17b4b741b86c810d99e453ee2/src/lib.rs#L49).

So it seems to me that the shortest path could be to fork cryptonight-hash, fix the slice-cast (yanked) dep then impl the missing variants using the C++ code as a guide.

Does that approach sound reasonable to you?

**Comment by Boog900** [comment]
If im honest I would rather a fresh start, that crate does a few things I don't like the look of, like using a lot of unsafe Rust. It may still be useful as an example though.

one of the comments even say:
`This is pretty much rustified C-code.`

Here is the link to the CryptoNight standard: https://web.archive.org/web/20190911221902/https://cryptonote.org/cns/cns008.txt 

Although starting from scratch will be more effort and I don't want to push a load of work on someone trying to help out I do feel in the long run starting from scratch will be better.

If you have Matrix it may be worth communicating on there: @Boog900:monero.social

**Comment by dan-da** [comment]
Ok, that's fair.   Yeah I wasn't aware of all the unsafe until I started trying to get it to build last night.  Which I finally succeeded and it passes tests with aesni feature disabled, but segvs when enabled.  Unfortunately one of the 2 yanked crates is no longer even on github.  I don't plan to proceed any further with that.  Code that builds is [here](https://github.com/dan-da/cryptonight-hash).

Well I can probably take a crack at a from-scratch impl.  might get in over my head, we'll see.

don't have matrix.   will see about setting it up later.

**Comment by detherminal** [comment]
I have implemented some basic functions of Monero in Rust for key derivations (sc_reduce etc.): [libmonero](https://github.com/monumexyz/libmonero). I can extract the basic processes of it if you list the needed processes. (To don't reinvent the wheel, of course used other libraries that implemented some functions)

**Comment by detherminal** [comment]
For anybody looking this at the future time, [I have implemented](https://github.com/monumexyz/libmonero/blob/main/src/crypt/cryptonight/slow_hash.rs) the CryptoNight algorithm pure-Rust based on the [original whitepaper](https://web.archive.org/web/20190911221902/https://cryptonote.org/cns/cns008.txt). The problem is, Monero doesn't use the exact same algorithm as the original paper described. If you want to start working on this, checking the code might help you.

**Comment by Boog900** [comment]
@detherminal I am pretty sure this line is UB as you are casting a pointer from a potentially unaligned u8 array to a u64 which has a higher alignment requirement: https://github.com/monumexyz/libmonero/blob/main/src/crypt/cryptonight/slow_hash.rs#L116

**Comment by detherminal** [comment]
Yeah, there may be problems because of the unsafe code but I don't want to work on it anymore 😄

**Comment by Boog900** [comment]
> we can be sure that it works successfull as it gives the same output as the whitepaper

With UB successful runs are possible, but the behavior is not guaranteed, which means it could stop working arbitrarily.

**Comment by dimalinux** [comment]
Can this issue be assigned to me? I have a version that is fully working and didn't require the use of unsafe at all (except maybe in certain trusted libraries that it uses like RustCrypto).
https://github.com/dimalinux/cuprate/tree/dimalinux/cryptonote

I still have some documentation, cleanups and additional tests to add before creating the PR. I'll also remove the C code completely. Right now my branch has lots of changes to the C code to make porting and generating test cases over smaller subsets of the code easier. Just ignore those changes if you take a peek at the code before I create the PR.

@vorot93 What you wrote about the CryptoNote hash not being used anymore is mostly true, but not 100% true. If you have a password on a pre-Polyseed mnemonic phrase, version 0 of the hash is used as part of the algorithm to generate the private key.
